server:
  port: 12345
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .jsp

  aop:
    proxy-target-class: true

##数据库链接池配置
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/simple?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 123
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true

##mybatis配置
mybatis:
  configuration:
    aggressive-lazy-loading: true
    cache-enabled: true
    default-fetch-size: 1000
    default-statement-timeout: 30000
  type-aliases-package: com.simple.demo.mapper
  mapper-locations: classpath:mappings/jdbcmapper/*.xml

##es配置
  elasticsearch:
    bboss:
      elasticsearch:
        rest:
          hostNames: 127.0.0.1:9200
        dateFormat: yyyy-MM-dd
        timeZone: Asiz/Shanghai
        ttl: 2d
        showTemplate: true
        discoverHost: true
      dslfile:
        refreshInterval: -1

      ##es client http连接池配置
      http:
        timeoutConnection: 5000
        timeoutScoket: 5000
        connectionRequestTimeout: 5000
        retryTime: 1
        maxLineLength: -1
        maxHeaderCount: 200
        maxTotal: 400
        defaultMaxPerRoute: 200
        soReuseAddress: false
        soKeepAlive: false
        timeToLive: 3600000
        keepAlive: 3600000
  output:
    ansi:
      enabled: always